### Crear un producto
POST http://localhost:1234/compras/producto
Content-Type: application/json

{
    "ID_Proveedor": 99,
    "NombreP" : "Carne",
    "Unidades" : "kilogramos",
    "Consumo" : "gramos"
}

### Modificar un producto por su id
PATCH  http://localhost:1234/compras/producto/7
Content-Type: application/json

{
    "ID_Proveedor": 67,
    "NombreP" : "Harina de maiz",
    "Unidades" : "bultos",
    "Consumo" : "kg"
}

### Eliminar un producto por su id
DELETE http://localhost:1234/compras/producto/8

### Crear una orden de compra
POST http://localhost:1234/historial
Content-Type: application/json

{
    "FECHA" : "2024-07-10T14:30:00Z",   
    "Pago" : "Contado",
    "Producto" : "Leche",  
    "Cantidad" : 60,
    "Precio": 333.0,  
    "Nombre_Proveedor" : "El Tunal",  
    "Autorizacion": "Gernente General: Samuel Molina" 
}

### Crear un proveedor
POST http://localhost:1234/compras/proveedores
Content-Type: application/json

{
    "rif" : "321456789",   
    "nombre_empresa" : "La Hacienda",
    "Dire_Fiscal" : "Calle Local Parcela Nro 20 Urb Industrial Valencia",  
    "Correo" : "lahacienda@gmail.com",
    "nombre_responsa": "Darwin Machis",  
    "Tlf" : "04245657890",  
    "ProveedorProd": "Carne" 
}

### Modificar un registro por su rif 
PATCH  http://localhost:1234/compras/proveedores/321456789
Content-Type: application/json

{ 
    "nombre_empresa" : "Polar CA",
    "Dire_Fiscal" : "Calle 123 Parcela Nro 11 Urb Industrial Maracay",  
    "Correo" : "polar@gmail.com",
    "nombre_responsa": "Romo",  
    "Tlf" : "04145659888",  
    "ProveedorProd": "Harina de maiz" 
}

### Eliminar un proveedor por su rif
DELETE http://localhost:1234/compras/proveedores/321456789

### Obtener un proveedor por su id
GET http://localhost:1234/compras/proveedores/321456789

### Crear una requisicion (solicitud)
POST http://localhost:1234/compras/solicitud
Content-Type: application/json

{
    "depar" : "Cocina",   
    "codigo_empleado" : 324,
    "codigo_producto" : 3,
    "nombre_producto" : "Pasta",  
    "fecha" : "2024-07-06T14:30:00Z",
    "detalle": "Baja en el minimo del producto en el almacen"
}

### Eliminar una requisicion por su id
DELETE http://localhost:1234/compras/solicitud/3

### Actualizar una requisicion por su id
PATCH  http://localhost:1234/compras/solicitud/3
Content-Type: application/json

{
    "depar" : "Cocina",   
    "codigo_empleado" : 324,
    "codigo_producto" : 3,
    "nombre_producto" : "Pasta",  
    "fecha" : "2024-07-06T14:30:00Z",
    "detalle": "Baja en el minimo del producto en el almacen"
}

### Obtener una solicitud por su id
GET http://localhost:1234/compras/solicitud/3